# 
# VYSOKE UCENI TECHNICKE V BRNE 
# Fakulta informacnich technologii 
# 
# Projekt FLP: Interpret imperativneho jazyka FLP-2014-C 
# Autori: [VEDUCI] Bc. Antolik David, xantol01@stud.fit.vutbr.cz 
# Bc. Kollar Jaroslav, xkolla03@stud.fit.vutbr.cz 
# Bc. Kollat Samuel, xkolla04@stud.fit.vutbr.cz 
# Bc. Kovacik Dusan, xkovac34@stud.fit.vutbr.cz

CC=ghc

all: interpret.hs
	$(CC) interpret.hs -o xantol01
